### ISSUE TITLE
Commas arent recognized

### ISSUE THREAD

**Issue by diegodorado** [gibber-cc/tidal.pegjs#2]
```js
console.log(parser.parse('[bd,hh]'))
```
outputs
```js
{ '0': { '0': { type: 'string', value: 'bd' }, type: 'group' },
  '1/2': { '0': { type: 'string', value: 'hh' }, type: 'group' },
  type: 'layer' }
```
instead of
```js
{ '0': { '0': { type: 'string', value: 'bd' }, type: 'group' },
  '0': { '0': { type: 'string', value: 'hh' }, type: 'group' },
  type: 'layer' }

```

**Comment by charlieroberts** [comment]
Yeah, it seems like the unit test for layers (polyrhythms) is wrong. We're in the middle of a big refactor (in the functional branch) that will definitely fix this, but it's still not usable yet. I will update this issue when it's done.

**Comment by charlieroberts** [comment]
Hi Diego,

I think this is safe to close now... the functional branch has been pulled into master and things work much better in general. There are also a bunch of tests for layers (polyrhythms) specifically, both parsing and querying (https://github.com/gibber-cc/tidal.pegjs/blob/master/test/test-layer.js). You'll need to use the new objects, but then should be good to go! Let me know if you have problems.

**Comment by diegodorado** [comment]
Hi Charlie!, thank you very much.
I was a little busy... I will try the new parser very soon and I tell how it went.
thanx
